# values.yaml
dagster:
  module: dagster
  environment: dev
  # values.yaml
  replicaCount: 1
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 3000 # attention dagster ecoute sur 3000
    targetPort: 3000
  container:
    port: 3000
