# dagster-components/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-workspace
  namespace: {{ .Release.Namespace }}
data:
  workspace.yaml: |-
    {{- .Files.Get .Values.dagster.workspace.file | nindent 4 }}