apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.module }}-{{ .Values.environment }}-config
  namespace: {{ .Release.Namespace }}
data:
  dagster.yaml: {{ .Files.Get "dagster.yaml" | nindent 4 }}