apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  dagster.yaml: |
    scheduler:
      module: dagster.core.scheduler
      class: DagsterDaemonScheduler

    run_coordinator:
      module: dagster.core.run_coordinator
      class: QueuedRunCoordinator

    run_storage:
      module: dagster_postgres.run_storage
      class: PostgresRunStorage
      config:
        postgres_db:
          hostname: {{ .Values.dagster.postgresql.external.host }}
          username: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          db_name: {{ .Values.dagster.postgresql.external.database }}
          port: {{ .Values.dagster.postgresql.external.port }}

    schedule_storage:
      module: dagster_postgres.schedule_storage
      class: PostgresScheduleStorage
      config:
        postgres_db:
          hostname: {{ .Values.dagster.postgresql.external.host }}
          username: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          db_name: {{ .Values.dagster.postgresql.external.database }}
          port: {{ .Values.dagster.postgresql.external.port }}

    event_log_storage:
      module: dagster_postgres.event_log
      class: PostgresEventLogStorage
      config:
        postgres_db:
          hostname: {{ .Values.dagster.postgresql.external.host }}
          username: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          db_name: {{ .Values.dagster.postgresql.external.database }}
          port: {{ .Values.dagster.postgresql.external.port }}

    compute_logs:
      module: dagster.core.storage.local_compute_log_manager
      class: LocalComputeLogManager
      config:
        base_dir: /opt/dagster/dagster_home/compute_logs